<a href="https://colab.research.google.com/github/jabsolo73/DAY1-ML/blob/main/Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
type(arr)

numpy.ndarray

In [5]:
arr1=np.zeros((2,2))
print(arr1)

[[0. 0.]
 [0. 0.]]


In [10]:
arr3=np.array([[4, 7 ,6],
             [7  ,7 ,9],
             [7  ,8 ,4]])
print(arr3)

[[4 7 6]
 [7 7 9]
 [7 8 4]]


In [17]:
 arr3 [2,0]


7

In [19]:
arr3 [2,2]

4

In [21]:
np.random.rand(3,2)


array([[0.52629306, 0.71949302],
       [0.23490462, 0.82218093],
       [0.6113558 , 0.25073914]])

In [23]:
arr1=np.random.rand(1,2)
arr2=np.random.rand(3,1)
arr3=np.add(arr1,arr2)
print(arr3)

[[1.24475731 1.46732546]
 [1.6270862  1.84965434]
 [0.86600484 1.08857298]]


In [34]:
a=[1,2,3,4,True,'jer',2,3,4,5,6,76,5,4,4,4,4,4,4,4,3,2,]
a[0:16:2]

[1, 3, True, 2, 4, 6, 5, 4]

In [38]:
a.reverse()

In [40]:
a

[1, 2, 3, 4, True, 'jer', 2, 3, 4, 5, 6, 76, 5, 4, 4, 4, 4, 4, 4, 4, 3, 2]